"""
CLI Module - Command-Line Interface Handlers

This module contains command handlers and argument parsing:
- commands: Command handler functions (cmd_*)
- argument_parser: CLI argument configuration
"""

from .commands import (
    cmd_init,
    cmd_add_correction,
    cmd_add_context_rule,
    cmd_list_context_rules,
    cmd_audit,
    cmd_list_corrections,
    cmd_export_corrections,
    cmd_import_corrections,
    cmd_run_correction,
    cmd_review_learned,
    cmd_approve,
    cmd_validate,
    cmd_health,
    cmd_metrics,
    cmd_config,
    cmd_migration,
    cmd_audit_retention,
    cmd_report_false_positive,
    cmd_load_presets,
    cmd_extract_uncertain,
    cmd_enqueue_review,
    cmd_list_review,
    cmd_show_review,
    cmd_attach_authority,
    cmd_reanchor_review,
    cmd_resolve_review,
    cmd_scan_traps,
    cmd_probe,
    cmd_close_sidecars,
    cmd_lookup,
)
from .argument_parser import create_argument_parser

__all__ = [
    'cmd_init',
    'cmd_add_correction',
    'cmd_add_context_rule',
    'cmd_list_context_rules',
    'cmd_audit',
    'cmd_list_corrections',
    'cmd_export_corrections',
    'cmd_import_corrections',
    'cmd_run_correction',
    'cmd_review_learned',
    'cmd_approve',
    'cmd_validate',
    'cmd_health',
    'cmd_metrics',
    'cmd_config',
    'cmd_migration',
    'cmd_audit_retention',
    'cmd_report_false_positive',
    'cmd_load_presets',
    'cmd_extract_uncertain',
    'cmd_enqueue_review',
    'cmd_list_review',
    'cmd_show_review',
    'cmd_attach_authority',
    'cmd_reanchor_review',
    'cmd_resolve_review',
    'cmd_scan_traps',
    'cmd_probe',
    'cmd_close_sidecars',
    'cmd_lookup',
    'create_argument_parser',
]
